-- CORE ENTITIES (USERS, PROJECTS, TEAMS, COMPANIES)
CREATE TABLE USERS (
    USER_ID UUID PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    COMPANY_ID UUID,
    STATUS VARCHAR(20) DEFAULT 'pending'
);

CREATE TABLE PROJECTS (
    PROJECT_ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    OWNER_ID UUID NOT NULL REFERENCES USERS(USER_ID),
    BUDGET NUMERIC(15,3),
    STATUS VARCHAR(20) DEFAULT 'active'
);

CREATE TABLE TEAMS (
    TEAM_ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COMPANY_ID UUID,
    LEADER_ID UUID REFERENCES USERS(USER_ID)
);

CREATE TABLE COMPANIES (
    COMPANY_ID UUID PRIMARY KEY,
    COMPANY_NAME VARCHAR(100) NOT NULL,
    INDUSTRY VARCHAR(100)
);

-- AI MODULES
CREATE TABLE AI_ASSISTANCE_SESSIONS (
    SESSION_ID UUID PRIMARY KEY,
    USER_ID UUID NOT NULL REFERENCES USERS(USER_ID),
    STATUS VARCHAR(20) DEFAULT 'active'
);

CREATE TABLE AI_INTERACTIONS (
    INTERACTION_ID UUID PRIMARY KEY,
    SESSION_ID UUID NOT NULL REFERENCES AI_ASSISTANCE_SESSIONS(SESSION_ID),
    USER_MESSAGE TEXT NOT NULL,
    AI_RESPONSE TEXT NOT NULL
);

CREATE TABLE AI_RECOMMENDATIONS (
    RECOMMENDATION_ID UUID PRIMARY KEY,
    USER_ID UUID NOT NULL REFERENCES USERS(USER_ID),
    PROJECT_ID UUID REFERENCES PROJECTS(PROJECT_ID)
);

-- COLLABORATION
CREATE TABLE COLLABORATION_SESSIONS (
    SESSION_ID UUID PRIMARY KEY,
    CREATED_BY UUID NOT NULL REFERENCES USERS(USER_ID),
    ENTITY_TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE SHARED_WHITEBOARDS (
    WHITEBOARD_ID UUID PRIMARY KEY,
    CREATED_BY UUID NOT NULL REFERENCES USERS(USER_ID),
    PROJECT_ID UUID REFERENCES PROJECTS(PROJECT_ID)
);

-- SECURITY
CREATE TABLE SECURITY_INCIDENTS (
    INCIDENT_ID UUID PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AFFECTED_USER_ID UUID REFERENCES USERS(USER_ID)
);

CREATE TABLE AUDIT_LOGS (
    LOG_ID UUID PRIMARY KEY,
    USER_ID UUID REFERENCES USERS(USER_ID),
    ACTION_TYPE VARCHAR(50) NOT NULL
);

-- FINANCIAL
CREATE TABLE BUDGET_ITEMS (
    ITEM_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL REFERENCES PROJECTS(PROJECT_ID),
    AMOUNT NUMERIC(15,2) NOT NULL
);

CREATE TABLE FINANCIAL_REPORTS (
    REPORT_ID UUID PRIMARY KEY,
    PROJECT_ID UUID NOT NULL REFERENCES PROJECTS(PROJECT_ID)
);

-- WEAK ENTITIES (Double-border in Chen notation)
CREATE TABLE USER_PROFILES (
    USER_ID UUID PRIMARY KEY REFERENCES USERS(USER_ID),
    BIO TEXT,
    SKILLS TEXT[]
);

CREATE TABLE TASK_COMMENTS (
    COMMENT_ID UUID PRIMARY KEY,
    TASK_ID UUID NOT NULL REFERENCES TASKS(TASK_ID),
    USER_ID UUID NOT NULL REFERENCES USERS(USER_ID)
);

-- RELATIONSHIP TABLES (M:N connections)
CREATE TABLE PROJECT_MEMBERS (
    PROJECT_ID UUID NOT NULL REFERENCES PROJECTS(PROJECT_ID),
    USER_ID UUID NOT NULL REFERENCES USERS(USER_ID),
    PRIMARY KEY (PROJECT_ID, USER_ID)
);

CREATE TABLE TEAM_MEMBERS (
    TEAM_ID UUID NOT NULL REFERENCES TEAMS(TEAM_ID),
    USER_ID UUID NOT NULL REFERENCES USERS(USER_ID),
    PRIMARY KEY (TEAM_ID, USER_ID)
);

-- FOREIGN KEY ADDITIONS (For explicit relationship detection)
ALTER TABLE USERS ADD CONSTRAINT fk_user_company 
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(COMPANY_ID);

ALTER TABLE TEAMS ADD CONSTRAINT fk_team_company 
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(COMPANY_ID);

-- Chen Notation Helpers (SQLDBM-specific comments)
COMMENT ON TABLE USER_PROFILES IS 'WEAK_ENTITY:USERS';
COMMENT ON TABLE TASK_COMMENTS IS 'WEAK_ENTITY:TASKS';
COMMENT ON TABLE PROJECT_MEMBERS IS 'RELATIONSHIP:USERS-PROJECTS';
COMMENT ON TABLE TEAM_MEMBERS IS 'RELATIONSHIP:USERS-TEAMS';